// Sample alerts data
export const alertsData = [
  {
    id: "1",
    createdAt: "2024-03-12T09:30:00Z",
    type: "email",
    productName: "Premium T-Shirt",
    message:
      "Stock level for Premium T-Shirt (TS-001) has fallen below the reorder level. Current stock: 18, Reorder level: 20.",
    read: false,
    productId: "1",
    sku: "TS-001",
  },
  {
    id: "2",
    createdAt: "2024-03-11T14:15:00Z",
    type: "sms",
    productName: "Leather Wallet",
    message: "URGENT: Leather Wallet (LW-003) is almost out of stock. Only 8 units remaining.",
    read: true,
    productId: "3",
    sku: "LW-003",
  },
  {
    id: "3",
    createdAt: "2024-03-10T11:45:00Z",
    type: "email",
    productName: "Smart Watch",
    message: "Smart Watch (SW-004) is now out of stock. Please reorder as soon as possible.",
    read: false,
    productId: "4",
    sku: "SW-004",
  },
  {
    id: "4",
    createdAt: "2024-03-09T16:20:00Z",
    type: "email",
    productName: "Wireless Headphones",
    message:
      "Stock level for Wireless Headphones (WH-002) is approaching reorder level. Current stock: 35, Reorder level: 10.",
    read: true,
    productId: "2",
    sku: "WH-002",
  },
  {
    id: "5",
    createdAt: "2024-03-08T10:05:00Z",
    type: "sms",
    productName: "Running Shoes",
    message: "Running Shoes (RS-005) inventory is getting low. Current stock: 12, Reorder level: 12.",
    read: false,
    productId: "5",
    sku: "RS-005",
  },
  {
    id: "6",
    createdAt: "2024-03-07T13:40:00Z",
    type: "email",
    productName: "Premium T-Shirt",
    message: "Weekly inventory report: Premium T-Shirt (TS-001) sales have increased by 15% this week.",
    read: true,
    productId: "1",
    sku: "TS-001",
  },
  {
    id: "7",
    createdAt: "2024-03-06T09:15:00Z",
    type: "sms",
    productName: "Smart Watch",
    message: "Restock alert: Smart Watch (SW-004) has been reordered and will arrive in 5 days.",
    read: false,
    productId: "4",
    sku: "SW-004",
  },
  {
    id: "8",
    createdAt: "2024-03-05T15:30:00Z",
    type: "email",
    productName: "Leather Wallet",
    message:
      "Inventory alert: Leather Wallet (LW-003) has been selling faster than expected. Consider increasing reorder level.",
    read: true,
    productId: "3",
    sku: "LW-003",
  },
  {
    id: "9",
    createdAt: "2024-03-04T11:20:00Z",
    type: "sms",
    productName: "Wireless Headphones",
    message: "New shipment of Wireless Headphones (WH-002) has arrived. Inventory updated to 35 units.",
    read: false,
    productId: "2",
    sku: "WH-002",
  },
  {
    id: "10",
    createdAt: "2024-03-03T14:50:00Z",
    type: "email",
    productName: "Running Shoes",
    message: "Running Shoes (RS-005) seasonal demand is expected to increase. Consider stocking up.",
    read: true,
    productId: "5",
    sku: "RS-005",
  },
]

